package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка работы поиска по наименованию оферты ")
    void searchValidationOfferTest() {

        step("Открываем сайт github", () -> {
            open("https://github.com/");
        });

        step("Вводим в поиске значение и нажимаем Enter", () -> {
            $("#user_email").setValue("23123").pressEnter();
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверка работы поиска по инн поставщика ")
    void searchValidationInnTest() {
        step("Открываем сайт 'https://github.com/'", () -> {
            open("https://github.com/");
        });
        step("Вводим в поиске значение и нажимаем Enter", () -> {
            $("[href=\"/team\"]").click();
        });
        step("Проверяем отображение страницы поиска", () -> {
            $(".container-lg").shouldBe(visible).shouldHave(text("Build like the best teams on the planet"));
        });
    }


}
